# gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: gcr.io/cloud-builders/npm
  args: ['install']
- name: gcr.io/cloud-builders/npm
  args: ['run', 'test:unit']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample', '.']

images: ['gcr.io/$PROJECT_ID/sample']