apiVersion: skaffold/v1beta7
kind: Config

build:
  artifacts:
  - image: gcr.io/dga-demo/proxy
    context: ./gaming-proxy
  - image: gcr.io/dga-demo/ref
    context: ./ref
  - image: gcr.io/dga-demo/game
    context: ./game
  - image: gcr.io/dga-demo/db
    context: ./db
  - image: gcr.io/dga-demo/ui
    context: ./ui
    sync:
      public/*: /app/public

profiles:
- name: cloud-build
  build:
    googleCloudBuild: {}
      # projectId: TODO
      # diskSizeGb: TODO
      # machineType: TODO
      # timeout:  TODO